// Code generated by ogen, DO NOT EDIT.

package api_1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateUser implements CreateUser operation.
//
// Creates a new user and returns it with an assigned ID.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *UserCreate) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements DeleteUser operation.
//
// Deletes a user and returns no content.
//
// DELETE /users/{id}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements GetUser operation.
//
// Retrieves a user by its unique identifier.
//
// GET /users/{id}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements ListUsers operation.
//
// Returns a list of all users.
//
// GET /users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements UpdateUser operation.
//
// Updates an existing user and returns the updated object.
//
// PUT /users/{id}
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UserUpdate, params UpdateUserParams) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
