// Code generated by ogen, DO NOT EDIT.
package api_1

type CreateUserRes interface {
	createUserRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserRes interface {
	getUserRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
