// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateUser implements CreateUser operation.
	//
	// Creates a new user and returns it with an assigned ID.
	//
	// POST /users
	CreateUser(ctx context.Context, req *UserCreate) (CreateUserRes, error)
	// DeleteUser implements DeleteUser operation.
	//
	// Deletes a user and returns no content.
	//
	// DELETE /users/{id}
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// GetUser implements GetUser operation.
	//
	// Retrieves a user by its unique identifier.
	//
	// GET /users/{id}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// ListUsers implements ListUsers operation.
	//
	// Returns a list of all users.
	//
	// GET /users
	ListUsers(ctx context.Context) (ListUsersRes, error)
	// UpdateUser implements UpdateUser operation.
	//
	// Updates an existing user and returns the updated object.
	//
	// PUT /users/{id}
	UpdateUser(ctx context.Context, req *UserUpdate, params UpdateUserParams) (UpdateUserRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
